### ISSUE TITLE
registering prefpane fails

### ISSUE THREAD

**Issue by retorquere** [windingwind/zotero-plugin-toolkit#14] opened 2023-02-02 15:45 UTC
I'm using the toolkit to load this prefpane: https://gist.github.com/988368e73613c8f3a44240afa7854ecf

but that gets me

<details><summary>error log</summary>

```
console.trace:
chrome://zotero-better-bibtex/content/better-bibtex.js 2907 log
chrome://zotero-better-bibtex/content/better-bibtex.js 3187 parseXHTMLToFragment
chrome://zotero-better-bibtex/content/better-bibtex.js 3660 node_modules/zotero-plugin-toolkit/dist/managers/preferencePane.js/register/onOpenWindow/<
console.groupEnd:
zotero(3)(+0000005): {"location":null}

console.groupCollapsed: ({})
console.trace:
chrome://zotero-better-bibtex/content/better-bibtex.js 2907 log
chrome://zotero-better-bibtex/content/better-bibtex.js 3661 node_modules/zotero-plugin-toolkit/dist/managers/preferencePane.js/register/onOpenWindow/<
console.groupEnd:
zotero(3)(+0000002): {}

JavaScript error: chrome://global/content/bindings/tabbox.xml, line 250: TypeError: children[i].getAttribute is not a function
JavaScript error: chrome://global/content/bindings/menulist.xml, line 236: TypeError: val.setAttribute is not a function
JavaScript error: chrome://global/content/bindings/menulist.xml, line 236: TypeError: val.setAttribute is not a function
JavaScript error: chrome://global/content/bindings/menulist.xml, line 236: TypeError: val.setAttribute is not a function
JavaScript error: chrome://global/content/bindings/menulist.xml, line 236: TypeError: val.setAttribute is not a function
JavaScript error: chrome://global/content/bindings/menulist.xml, line 236: TypeError: val.setAttribute is not a function
JavaScript error: chrome://global/content/bindings/menulist.xml, line 236: TypeError: val.setAttribute is not a function
JavaScript error: chrome://global/content/bindings/menulist.xml, line 236: TypeError: val.setAttribute is not a function
JavaScript error: chrome://global/content/bindings/menulist.xml, line 236: TypeError: val.setAttribute is not a function
JavaScript error: chrome://global/content/bindings/menulist.xml, line 236: TypeError: val.setAttribute is not a function
JavaScript error: chrome://global/content/bindings/menulist.xml, line 236: TypeError: val.setAttribute is not a function
..... lots more
```

</details>

**Comment by volatile-static** [comment] 2023-02-03 00:34
There is no need to add `<preference>` any more.
see
https://github.com/windingwind/zotero-plugin-template/blob/bootstrap/addon/chrome/content/preferences.xhtml

**Comment by windingwind** [comment] 2023-02-03 01:34
A real world example: https://github.com/windingwind/zotero-pdf-translate/blob/main/addon/chrome/content/preferences.xhtml

**Comment by retorquere** [comment] 2023-02-03 07:12
* on zotero-dev it was said that `<preferences>` would be inert but allowed to be present
* I get the same problem on https://gist.github.com/5e2ae0cd8204861b38f4e61ec70bdd67

**Comment by windingwind** [comment] 2023-02-03 09:24
Does this xhtml work on Zotero7? Not sure if this is a bug with toolkit or xhtml itself.

As the <prefs> does not have any effect, it is natural not to support them. If you have to use a xhtml with <prefs>, maybe an extra regex in toolkit after loading the xhtml. They’ll be ignored anyway.

**Comment by windingwind** [comment] 2023-02-03 09:54
I haven’t tried but it seems like the problem is related to tabbox. Maybe they cannot be correctly created with createElementNS? Not sure.

As Z7 suggests developers use groupbox instead of tabbox, I don’t use tabbox anymore. I’ll try your xhtml when I have time.

**Comment by volatile-static** [comment] 2023-02-03 13:47
@retorquere Could you show your code where you register this xhtml?

**Comment by retorquere** [comment] 2023-02-03 14:08
https://github.com/retorquere/zotero-better-bibtex/blob/zpt/content/prefs.ts#L6-L68 (the errors appear regardless of whether I have the load handler present)

**Comment by retorquere** [comment] 2023-02-03 14:12
> As Z7 suggests developers use groupbox instead of tabbox, I don’t use tabbox anymore. I’ll try your xhtml when I have time.

That strikes me as strange, because tabbox and groupbox do very different things. How would I get the behavior where you would see a particular pane only when the corresponding tab is selected?

I don't see any mention of tabboxes on zotero-dev or https://www.zotero.org/support/dev/zotero_7_for_developers

**Comment by retorquere** [comment] 2023-02-03 14:13
I do see the icon appear in the preferences window BTW, and I see prefs being attached to controls, so the loading appears to at least partially work.

**Comment by windingwind** [comment] 2023-02-03 17:05
The Zotero team did not say tabbox is not recommended, while they do not use it anymore. In Z7, the settings that used to be in tabbox are now flattened and in groupbox.

Z7 provides a registration option called subpanel, which creates a hidden panel.

However it is not that easy to implement in Z6. So I would rather not use this subpanel. And actually it is not a tabbox.

I think flatten the settings is natural and reasonable, especially considering that in Z7 the page is scrollable (and in Z6 with toolkit).

**Comment by windingwind** [comment] 2023-02-03 17:42
As a developer I know how painful it is to change these prefs to the Zotero 7’s behavior. I spent weeks doing this on my several plugins. I hated the styles and strange xul elements. They breaks the style, cause unexpected line breaks, and sometimes don’t even appear in Z7. (The menulist is invisible in about:blank window). It’s time for XUL elements to retire.

**Comment by retorquere** [comment] 2023-02-03 17:52
I personally liked XUL, and I'll miss it.

**Comment by windingwind** [comment] 2023-02-04 02:02
Ohh it’s only my personal opinion. The design of XUL elements are very cool. If they are not that buggy I would definitely love them.

**Comment by windingwind** [comment] 2023-02-05 13:28
I confirm the `<tabbox>` can be correctly created with the toolkit.

Zotero 6

![image](https://user-images.githubusercontent.com/33902321/216821784-c4d57493-d31d-4e00-8f85-e72b668406e6.png)

Zotero 7

![image](https://user-images.githubusercontent.com/33902321/216821893-5496d2e9-0b7b-4580-9764-72766182c9d5.png)

**Comment by windingwind** [comment] 2023-02-05 13:30
And the search of Zotero 7 also works with tabbox and its child elements in Zotero 7.

**Comment by windingwind** [comment] 2023-02-05 13:47
I figured out why: the `<menulist>` item cannot be correctly created with DOMParser in Zotero 6. This is a normal menulist:

![image](https://user-images.githubusercontent.com/33902321/216822317-6b51594c-9577-437f-b1dd-e74cf9426fb9.png)

and this is what DOMParser gives us:

![image](https://user-images.githubusercontent.com/33902321/216822337-3a6c9f02-79ea-4cbc-9b58-72a80a323ad2.png)

Some anonymous elements are not created and this causes the bugs you mentioned above.

My workaround is to put a placeholder element and replace them using `ztoolkit.UI.replaceElement`.

**Comment by retorquere** [comment] 2023-02-05 14:25
Would HTML select/option be a working replacement?

**Comment by windingwind** [comment] 2023-02-05 14:58
> Would HTML select/option be a working replacement?

Yes, it works on Zotero 6 but fails on Zotero 7 (the popup doesn't show up). I dug deep into the firefox code to see why this happens and it turns out the popup on newer firefox versions requires the window to be somehow initialized while the preference (and most of the other windows) are not.

I made a workaround for the `select` elements on Zotero 7 here: 

https://github.com/windingwind/zotero-plugin-toolkit/blob/160dda6dcc347bd73d57d408156fba69163a854a/src/helpers/dialog.ts#L386-L467

Anyway, it is very annoying. So my suggestion is to create the menulist in the script instead of XHTML.

**Comment by retorquere** [comment] 2023-02-05 18:20
I'll just first see if I can sensibly replace them with radiobuttons instead. Thanks for the deep-dive BTW.

**Comment by retorquere** [comment] 2023-03-01 14:46
I can set that with an option I see. I have partial success when I register [this prefpane](https://gist.github.com/7201b9456bee142d751a84b4169b68d0) using

```js
manager.register({
      pluginID: 'zotero-better-bibtex',
      src: 'chrome://zotero-better-bibtex/content/preferences.xhtml',
      label: 'Better BibTeX',
      image: 'chrome://zotero-better-bibtex/skin/bibtex.svg',
      extraDTD: ['chrome://zotero-better-bibtex/locale/overlay.dtd'],
      defaultXUL: true,
      onload: async (win: Window) => {
        log.debug('loading prefpane')
        this.window = win
        await this.load()
        log.debug('loading prefpane done')
        win.addEventListener('unload', () => {
          log.debug('unloading prefpane')
          this.unload()
          this.window = null
          log.debug('unloading prefpane done')
        })
      },
    })
```

but a part of the UI is missing, and the error log has


```
JavaScript error: chrome://global/content/bindings/tabbox.xml, line 250: TypeError: children[i].getAttribute is not a function
JavaScript error: chrome://global/content/bindings/tabbox.xml, line 250: TypeError: children[i].getAttribute is not a function
JavaScript error: chrome://global/content/bindings/tabbox.xml, line 250: TypeError: children[i].getAttribute is not a function
JavaScript error: chrome://zotero/content/bindings/preferences-mac.xml, line 148: TypeError: this.preferences.rootBranchInternal is undefined
JavaScript error: chrome://zotero/content/bindings/preferences-mac.xml, line 148: TypeError: this.preferences.rootBranchInternal is undefined
[lots and lots of this last line]
```

**Comment by retorquere** [comment] 2023-03-02 07:47
How can I add CSS to the loaded prefpane?

**Comment by windingwind** [comment] 2023-03-02 08:18
The CSS can be hard-coded in the `xhtml`. If you want them to be loaded after the window is ready, please add the loading CSS action, which could be a `createElement` call,  to the `onload` event callback.


See also:

https://github.com/windingwind/zotero-plugin-template/blob/c4777e35a9aca591d5e52d743cdd376e9a18f5bd/addon/chrome/content/preferences.xhtml#L1-L4

https://github.com/windingwind/zotero-plugin-template/blob/c4777e35a9aca591d5e52d743cdd376e9a18f5bd/src/modules/preferenceScript.ts#L4-L42

**Comment by retorquere** [comment] 2023-03-02 08:52
> The CSS can be hard-coded in the xhtml

You mean on each individual element? I'd like to avoid that if possible.

> which could be a createElement call, to the `onload` event callback.

So create a `<style>` element? can those exist interleaved with the HTML body?

**Comment by retorquere** [comment] 2023-03-02 09:03
> Anyway, it is very annoying. So my suggestion is to create the menulist in the script instead of XHTML.

Will preferences be bound to dynamically created menulists? I will need something like `menulist`, I tried replacing them all with radiobuttons and that just makes the UI way too big.

What a pain this is. I'm glad your toolkit exists, but this should have been the easiest part of a transition towards Z7 and it's just not working so far.

**Comment by retorquere** [comment] 2023-03-02 12:14
I tried injecting a processing instruction to load a css file but that doesn't seem to do anything.

**Comment by windingwind** [comment] 2023-03-02 14:55
I'll test the <style> or <link> element in the prefs pane ASAP.

The bounding only happens once, that is the moment the page is loaded. Maybe we could add some API for manually binding elements in the toolkit. It wouldn't be too complex to bind them manually.

I hate UI works too. I believe Zotero developers would also agree, as they seem to not like this part as well and leave these to us, LOL.

**Comment by retorquere** [comment] 2023-03-02 15:01
I've replaced all tabboxes and menulists and have now this: https://gist.github.com/fbef32f6d7022d1f74ac5c8e584c75f6

That takes care of the errors that using tabboxes yielded, but I'm now stuck on a single error:

```
JavaScript error: chrome://zotero/content/bindings/preferences-mac.xml, line 1277: TypeError: preference is null
```

I've looked in the Zotero source, and it means it knows the name of a preference, assumes there is an element for it with that as its ID, and there apparently isn't.

Driving me nuts, and I need to fix this one way or the other. In my latest release, my prefs screen is broken on windows (of course), and I figured this would be a good time to migrate to xhtml prefs.

**Comment by windingwind** [comment] 2023-03-03 03:37
@retorquere 

I test the `<style>` on Z6 and it works. Use `createElementNS("http://www.w3.org/1999/xhtml", "style")` or the `createElement` API provided by the toolkit to automatically decide the namespace.

![image](https://user-images.githubusercontent.com/33902321/222625125-418bf452-cb26-4a30-baa5-ba22558aff3a.png)

**Comment by windingwind** [comment] 2023-03-03 04:46
The `<link>` element also works.

code:

```ts
const stylesheet = ztoolkit.UI.createElement(
  addon.data.prefs?.window.document!,
  "link",
  {
    properties: {
      type: "text/css",
      rel: "stylesheet",
      href: `chrome://${config.addonRef}/content/zoteroPane.css`,
    },
  }
);
addon.data.prefs?.window.document
  .querySelector(`#zotero-prefpane-${config.addonRef}`)
  ?.append(stylesheet);
```

make the title red:
![image](https://user-images.githubusercontent.com/33902321/222633595-0c248125-a253-403d-8aa2-c84861885a56.png)

**Comment by retorquere** [comment] 2023-03-03 07:14
I should be able to just add that to the xhtml, no? It didn't work when I tried yesterday, but I'll give it another go.

**Comment by retorquere** [comment] 2023-03-03 07:31
I've tried this: https://gist.github.com/68d4e302d17dad84fcaf0037dafcb0ff, but that still doesn't apply the style (I've checked through the translator editor that the URL is correct), and I still have the one 

```
JavaScript error: chrome://zotero/content/bindings/preferences-mac.xml, line 1277: TypeError: preference is null
```

**Comment by retorquere** [comment] 2023-03-03 07:41
I've simplified the lot down to just a few elements, and this doesn't work for me. No error, but no CSS applied: https://gist.github.com/6ecaa2e01b89d491f39438aacb471eaa

**Comment by retorquere** [comment] 2023-03-03 07:50
Inlining the style also doesn't seem to apply the CSS: https://gist.github.com/0e70d2a5126ab326a6f4980561053cc3

**Comment by windingwind** [comment] 2023-03-03 08:02
This works for me, both the style and link element:

![image](https://user-images.githubusercontent.com/33902321/222664808-93b355ce-1328-4b25-80e1-28a483d20331.png)

**Comment by windingwind** [comment] 2023-03-03 08:05
Not sure what's happening with MacOS, as I don't own a Mac device. Does this error still there when prefs are all removed, and what happens when adding them back one by one?

**Comment by retorquere** [comment] 2023-03-03 08:21
That was it, the inline style works!

That still leaves the "preference is null" error. Any hints on how I can find out what the name of the preference is?

**Comment by retorquere** [comment] 2023-03-04 07:53
OMG this is so frustrating. I'm trying to narrow down why parsing fails, any clue? I have whittled it down to this

```
const xml = `
<!DOCTYPE bindings [ <!ENTITY % _dtd-0 SYSTEM "chrome://zotero-better-bibtex/locale/zotero-better-bibtex.dtd"> %_dtd-0; ]>
<html:div xmlns="http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul" xmlns:xul="http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul" xmlns:html="http://www.w3.org/1999/xhtml">
 <xul:prefpane></xul:prefpane>
</html:div>`

Components.utils.import('resource://gre/modules/Services.jsm')
const parser = Components.classes['@mozilla.org/xmlextras/domparser;1'].createInstance(Components.interfaces.nsIDOMParser)
const xul = parser.parseFromString(xml, 'text/xml')
xul.documentElement.textContent
```

but the mere presence of xul elements causes parsing to fail. If I change the `http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul` into anything else, it succeeds.

**Comment by windingwind** [comment] 2023-03-04 10:39
I remember the nsIDOMParser might be different from the DOMParser in main window. Sorry I am really busy these days, I will try to test this.

**Comment by retorquere** [comment] 2023-03-04 10:46
If I try this in de JS runner, I get no output at all

```
const xml = `
<!DOCTYPE bindings [ <!ENTITY % _dtd-0 SYSTEM "chrome://zotero-better-bibtex/locale/zotero-better-bibtex.dtd"> %_dtd-0; ]>
<html:div xmlns="http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul" xmlns:xul="http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul" xmlns:html="http://www.w3.org/1999/xhtml">
 <xul:prefpane></xul:prefpane>
</html:div>`

//Components.utils.import('resource://gre/modules/Services.jsm')
//const parser = Components.classes['@mozilla.org/xmlextras/domparser;1'].createInstance(Components.interfaces.nsIDOMParser)
let x = 'x'
try {
    const parser = new DOMParser
    const xul = parser.parseFromString(xml, 'text/xml')
    x = xul.documentElement.textContent
} catch (err) {
    x = err.message
}
x
```

**Comment by retorquere** [comment] 2023-03-04 10:49
Using `new DOMParser` works. And tabboxes load without issue apparently, so I don't need inline CSS to emulate them.

**Comment by windingwind** [comment] 2023-04-01 15:47
Hi @retorquere , is this issue solved already?

**Comment by retorquere** [comment] 2023-04-01 16:11
No, and I'm giving up. I'm going to load my prefs in a separate window where I can just load my existing xul prefs. I need to get moving on getting BBT restartless.

**Comment by windingwind** [comment] 2023-04-02 02:02
It pitty the toolkit failed to work with BBT... Thanks for your time and patience. As a Zotero and BBT user, I am always dreaming about having these settings of different plugins in one window. However, seem like it is not possible right now, as long as these Zotero-side issues still exist with the prefs window.

**Comment by retorquere** [comment] 2023-04-02 10:37
They will be once again when BBT goes zotero-7-only.

**Comment by windingwind** [comment] 2023-04-02 15:24
To anyone who would be interested in this topic, a possible middle way at this time is to use the least XUL elements in an XHTML from now on, which can be opened as a window on both Z6 and Z7. Once Zotero 6 is no longer maintained, moving to pure XHTML will not be that difficult. From any perspective, HTML is more or less a stable standard than XUL.

The plugin better-notes uses 10+ XUL/HTML files/windows. From the very beginning of this plugin development, I only use XUL if the window requires privilege, otherwise, it should be in pure HTML. In the last 2 months, I have finished most of the work to make it run on both Z6 and Z7. It turns out that using the least XUL elements is very wise and saved me a loooot of time to rewrite these UI things.

**Comment by retorquere** [comment] 2023-04-02 15:38
I've tried minimizing xul, including a css +xhmtl tabs replacement, and I still couldn't get rid of all errors.

**Closed** 2023-11-05 14:14 UTC
